-- PropIntel Supabase Schema
-- Copy and paste this into the Supabase SQL Editor and click "Run"

-- 1. Create Properties Table
CREATE TABLE IF NOT EXISTS public.properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price TEXT NOT NULL,
    location TEXT NOT NULL,
    property_type TEXT,
    match_score INTEGER,
    status TEXT DEFAULT 'Active',
    ai_intel TEXT,
    image_name TEXT,
    views INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Buyer Profiles Table
CREATE TABLE IF NOT EXISTS public.buyer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    contact TEXT,
    preferred_location TEXT[],
    min_budget INTEGER,
    max_budget INTEGER,
    urgency TEXT,
    property_type TEXT,
    ai_analysis JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Visits Table
CREATE TABLE IF NOT EXISTS public.visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property TEXT NOT NULL,
    location TEXT NOT NULL,
    buyer TEXT NOT NULL,
    time TEXT NOT NULL,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Disable Row Level Security (RLS) for the MVP Prototype
-- Warning: This allows unrestricted read/write access. For a production app, you would enable RLS and write policies.
ALTER TABLE public.properties DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.buyer_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.visits DISABLE ROW LEVEL SECURITY;

-- 5. Enable Realtime subscriptions
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table properties;
alter publication supabase_realtime add table buyer_profiles;
alter publication supabase_realtime add table visits;
